# Generated by Django 2.0.6 on 2018-06-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='VIN',
            field=models.CharField(max_length=17),
        ),
    ]
