# Generated by Django 2.0.6 on 2018-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='miles_driven',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
