# Generated by Django 2.0.6 on 2018-07-04 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20180702_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=85.99, max_digits=8),
        ),
    ]
