# Generated by Django 2.0.6 on 2018-06-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180611_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeID',
        ),
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
