# Generated by Django 2.0.6 on 2018-06-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20180611_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AddField(
            model_name='store',
            name='storeID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
