# Generated by Django 2.0.6 on 2018-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20180611_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeID',
        ),
        migrations.AddField(
            model_name='store',
            name='StoreID',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False),
        ),
    ]
