# Generated by Django 2.0.6 on 2018-07-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('m', 'Maintenance'), ('a', 'Available'), ('r', 'Reserved')], default='a', max_length=1),
        ),
    ]
