# Generated by Django 2.0.6 on 2018-06-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20180611_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='StoreID',
            new_name='storeID',
        ),
    ]
