# Generated by Django 2.0.6 on 2018-06-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20180611_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='storeID',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
