# Generated by Django 2.0.6 on 2018-07-24 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_maintenance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('date', models.DateTimeField()),
                ('payment_type', models.CharField(choices=[('i', 'In Store'), ('v', 'Visa'), ('m', 'Mastercard'), ('a', 'American Express')], default='i', max_length=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Reservation')),
            ],
        ),
    ]
