# Generated by Django 2.0.6 on 2018-07-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180723_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='gas_milage',
            new_name='gas_mileage',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('vr6', 'VR6'), ('v4', 'V4'), ('v8', 'V8'), ('v6', 'V6'), ('i4', 'Inline 4'), ('w8', 'W8'), ('i6', 'Inline 6'), ('e', 'Electric'), ('h', 'Hybrid')], default='i4', max_length=3),
        ),
    ]
