# Generated by Django 2.0.6 on 2018-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180612_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, upload_to='vehicle_photos'),
        ),
    ]
