# Generated by Django 2.0.6 on 2018-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20180723_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('i4', 'Inline 4'), ('i6', 'Inline 6'), ('v4', 'V4'), ('v6', 'V6'), ('v8', 'V8'), ('w8', 'W8'), ('vr6', 'VR6'), ('e', 'Electric'), ('h', 'Hybrid')], default='i4', max_length=3),
        ),
    ]
