# Generated by Django 2.0.6 on 2018-07-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180723_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('i', 'In Store'), ('v', 'Visa'), ('m', 'Mastercard'), ('d', 'Discover'), ('a', 'American Express')], default='i', max_length=1),
        ),
    ]
