# Generated by Django 2.0.6 on 2018-06-18 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_vehicle_loanee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='loanee',
        ),
    ]
